### ISSUE TITLE
Headers  not  found

### ISSUE THREAD

**Issue by srimanthtenneti** [krzhu/abc_py#2]
Hi, 

I am trying to make the abc_py and it is giving me some errors. Can you help me resolve this ?
![Screenshot from 2023-03-29 12-15-33](https://user-images.githubusercontent.com/40752683/228602141-bb3e52df-01de-4b77-9d35-a2b8525a1097.png)

Thanks in advance

**Comment by krzhu** [comment]
Check the README and set the environment variables.

**Comment by srimanthtenneti** [comment]
I already added the PYBIND11 and the ABC environment variables as per the README

**Comment by srimanthtenneti** [comment]
![Screenshot from 2023-03-28 10-17-16](https://user-images.githubusercontent.com/40752683/229009107-fc70ae6e-4644-43fc-b6b6-cadffdec1b7e.png)

**Comment by phyzhenli** [comment]
I replaced `abc_src` with the absolute path and it worked.   :)

**Comment by phyzhenli** [comment]
Or replace `abc_src` with `src`.
